tasks:
  - name: Docker-compose
    command: cd Docker && docker-compose up -d && gp sync-done prev

  - name: YottaDB-terminal
    command: gp sync-await prev && docker exec -it yottadb /opt/yottadb/current/ydb
    openMode: split-right
 
  - name: iKnow-terminal
    command:  gp sync-await prev && docker exec -it iknow /bin/bash -c "cd /home/iknow && bash"
    openMode: split-right
