tasks:
  - name: Docker-compose
    command: cd Docker && docker-compose up && gp sync-done prev

  - name: YottaDB-terminal
    init: gp sync-await prev
    command: docker exec -it yottadb /opt/yottadb/current/ydb
    openMode: split-right
 
  - name: iKnow-terminal
    init: gp sync-await prev
    command:  docker exec -it iknow /bin/bash -c "cd /home/iknow"
    openMode: split-right
